/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedResearcherHomeRouteImport } from './routes/_authenticated/researcher/home'
import { Route as AuthenticatedResearcherExplorerRouteImport } from './routes/_authenticated/researcher/explorer'
import { Route as AuthenticatedResearcherDownloadsRouteImport } from './routes/_authenticated/researcher/downloads'
import { Route as AuthenticatedResearcherCreateRouteImport } from './routes/_authenticated/researcher/create'
import { Route as AuthenticatedResearcherContractsRouteImport } from './routes/_authenticated/researcher/contracts'
import { Route as AuthenticatedResearcherCampaignsRouteImport } from './routes/_authenticated/researcher/campaigns'
import { Route as AuthenticatedResearcherAnalyticsRouteImport } from './routes/_authenticated/researcher/analytics'
import { Route as AuthenticatedPatientVaultRouteImport } from './routes/_authenticated/patient/vault'
import { Route as AuthenticatedPatientTimelineRouteImport } from './routes/_authenticated/patient/timeline'
import { Route as AuthenticatedPatientReferralsRouteImport } from './routes/_authenticated/patient/referrals'
import { Route as AuthenticatedPatientRedeemRouteImport } from './routes/_authenticated/patient/redeem'
import { Route as AuthenticatedPatientPrivacyRouteImport } from './routes/_authenticated/patient/privacy'
import { Route as AuthenticatedPatientPlacesRouteImport } from './routes/_authenticated/patient/places'
import { Route as AuthenticatedPatientMarketplaceRouteImport } from './routes/_authenticated/patient/marketplace'
import { Route as AuthenticatedPatientLeaderboardRouteImport } from './routes/_authenticated/patient/leaderboard'
import { Route as AuthenticatedPatientInteractionsRouteImport } from './routes/_authenticated/patient/interactions'
import { Route as AuthenticatedPatientInsightsRouteImport } from './routes/_authenticated/patient/insights'
import { Route as AuthenticatedPatientGoalsRouteImport } from './routes/_authenticated/patient/goals'
import { Route as AuthenticatedPatientEarningsRouteImport } from './routes/_authenticated/patient/earnings'
import { Route as AuthenticatedPatientDataNftRouteImport } from './routes/_authenticated/patient/data-nft'
import { Route as AuthenticatedPatientDashboardRouteImport } from './routes/_authenticated/patient/dashboard'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedResearcherHomeRoute =
  AuthenticatedResearcherHomeRouteImport.update({
    id: '/researcher/home',
    path: '/researcher/home',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearcherExplorerRoute =
  AuthenticatedResearcherExplorerRouteImport.update({
    id: '/researcher/explorer',
    path: '/researcher/explorer',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearcherDownloadsRoute =
  AuthenticatedResearcherDownloadsRouteImport.update({
    id: '/researcher/downloads',
    path: '/researcher/downloads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearcherCreateRoute =
  AuthenticatedResearcherCreateRouteImport.update({
    id: '/researcher/create',
    path: '/researcher/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearcherContractsRoute =
  AuthenticatedResearcherContractsRouteImport.update({
    id: '/researcher/contracts',
    path: '/researcher/contracts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearcherCampaignsRoute =
  AuthenticatedResearcherCampaignsRouteImport.update({
    id: '/researcher/campaigns',
    path: '/researcher/campaigns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResearcherAnalyticsRoute =
  AuthenticatedResearcherAnalyticsRouteImport.update({
    id: '/researcher/analytics',
    path: '/researcher/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientVaultRoute =
  AuthenticatedPatientVaultRouteImport.update({
    id: '/patient/vault',
    path: '/patient/vault',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientTimelineRoute =
  AuthenticatedPatientTimelineRouteImport.update({
    id: '/patient/timeline',
    path: '/patient/timeline',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientReferralsRoute =
  AuthenticatedPatientReferralsRouteImport.update({
    id: '/patient/referrals',
    path: '/patient/referrals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientRedeemRoute =
  AuthenticatedPatientRedeemRouteImport.update({
    id: '/patient/redeem',
    path: '/patient/redeem',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientPrivacyRoute =
  AuthenticatedPatientPrivacyRouteImport.update({
    id: '/patient/privacy',
    path: '/patient/privacy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientPlacesRoute =
  AuthenticatedPatientPlacesRouteImport.update({
    id: '/patient/places',
    path: '/patient/places',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientMarketplaceRoute =
  AuthenticatedPatientMarketplaceRouteImport.update({
    id: '/patient/marketplace',
    path: '/patient/marketplace',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientLeaderboardRoute =
  AuthenticatedPatientLeaderboardRouteImport.update({
    id: '/patient/leaderboard',
    path: '/patient/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientInteractionsRoute =
  AuthenticatedPatientInteractionsRouteImport.update({
    id: '/patient/interactions',
    path: '/patient/interactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientInsightsRoute =
  AuthenticatedPatientInsightsRouteImport.update({
    id: '/patient/insights',
    path: '/patient/insights',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientGoalsRoute =
  AuthenticatedPatientGoalsRouteImport.update({
    id: '/patient/goals',
    path: '/patient/goals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientEarningsRoute =
  AuthenticatedPatientEarningsRouteImport.update({
    id: '/patient/earnings',
    path: '/patient/earnings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientDataNftRoute =
  AuthenticatedPatientDataNftRouteImport.update({
    id: '/patient/data-nft',
    path: '/patient/data-nft',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientDashboardRoute =
  AuthenticatedPatientDashboardRouteImport.update({
    id: '/patient/dashboard',
    path: '/patient/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/patient/data-nft': typeof AuthenticatedPatientDataNftRoute
  '/patient/earnings': typeof AuthenticatedPatientEarningsRoute
  '/patient/goals': typeof AuthenticatedPatientGoalsRoute
  '/patient/insights': typeof AuthenticatedPatientInsightsRoute
  '/patient/interactions': typeof AuthenticatedPatientInteractionsRoute
  '/patient/leaderboard': typeof AuthenticatedPatientLeaderboardRoute
  '/patient/marketplace': typeof AuthenticatedPatientMarketplaceRoute
  '/patient/places': typeof AuthenticatedPatientPlacesRoute
  '/patient/privacy': typeof AuthenticatedPatientPrivacyRoute
  '/patient/redeem': typeof AuthenticatedPatientRedeemRoute
  '/patient/referrals': typeof AuthenticatedPatientReferralsRoute
  '/patient/timeline': typeof AuthenticatedPatientTimelineRoute
  '/patient/vault': typeof AuthenticatedPatientVaultRoute
  '/researcher/analytics': typeof AuthenticatedResearcherAnalyticsRoute
  '/researcher/campaigns': typeof AuthenticatedResearcherCampaignsRoute
  '/researcher/contracts': typeof AuthenticatedResearcherContractsRoute
  '/researcher/create': typeof AuthenticatedResearcherCreateRoute
  '/researcher/downloads': typeof AuthenticatedResearcherDownloadsRoute
  '/researcher/explorer': typeof AuthenticatedResearcherExplorerRoute
  '/researcher/home': typeof AuthenticatedResearcherHomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/patient/data-nft': typeof AuthenticatedPatientDataNftRoute
  '/patient/earnings': typeof AuthenticatedPatientEarningsRoute
  '/patient/goals': typeof AuthenticatedPatientGoalsRoute
  '/patient/insights': typeof AuthenticatedPatientInsightsRoute
  '/patient/interactions': typeof AuthenticatedPatientInteractionsRoute
  '/patient/leaderboard': typeof AuthenticatedPatientLeaderboardRoute
  '/patient/marketplace': typeof AuthenticatedPatientMarketplaceRoute
  '/patient/places': typeof AuthenticatedPatientPlacesRoute
  '/patient/privacy': typeof AuthenticatedPatientPrivacyRoute
  '/patient/redeem': typeof AuthenticatedPatientRedeemRoute
  '/patient/referrals': typeof AuthenticatedPatientReferralsRoute
  '/patient/timeline': typeof AuthenticatedPatientTimelineRoute
  '/patient/vault': typeof AuthenticatedPatientVaultRoute
  '/researcher/analytics': typeof AuthenticatedResearcherAnalyticsRoute
  '/researcher/campaigns': typeof AuthenticatedResearcherCampaignsRoute
  '/researcher/contracts': typeof AuthenticatedResearcherContractsRoute
  '/researcher/create': typeof AuthenticatedResearcherCreateRoute
  '/researcher/downloads': typeof AuthenticatedResearcherDownloadsRoute
  '/researcher/explorer': typeof AuthenticatedResearcherExplorerRoute
  '/researcher/home': typeof AuthenticatedResearcherHomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/_authenticated/patient/data-nft': typeof AuthenticatedPatientDataNftRoute
  '/_authenticated/patient/earnings': typeof AuthenticatedPatientEarningsRoute
  '/_authenticated/patient/goals': typeof AuthenticatedPatientGoalsRoute
  '/_authenticated/patient/insights': typeof AuthenticatedPatientInsightsRoute
  '/_authenticated/patient/interactions': typeof AuthenticatedPatientInteractionsRoute
  '/_authenticated/patient/leaderboard': typeof AuthenticatedPatientLeaderboardRoute
  '/_authenticated/patient/marketplace': typeof AuthenticatedPatientMarketplaceRoute
  '/_authenticated/patient/places': typeof AuthenticatedPatientPlacesRoute
  '/_authenticated/patient/privacy': typeof AuthenticatedPatientPrivacyRoute
  '/_authenticated/patient/redeem': typeof AuthenticatedPatientRedeemRoute
  '/_authenticated/patient/referrals': typeof AuthenticatedPatientReferralsRoute
  '/_authenticated/patient/timeline': typeof AuthenticatedPatientTimelineRoute
  '/_authenticated/patient/vault': typeof AuthenticatedPatientVaultRoute
  '/_authenticated/researcher/analytics': typeof AuthenticatedResearcherAnalyticsRoute
  '/_authenticated/researcher/campaigns': typeof AuthenticatedResearcherCampaignsRoute
  '/_authenticated/researcher/contracts': typeof AuthenticatedResearcherContractsRoute
  '/_authenticated/researcher/create': typeof AuthenticatedResearcherCreateRoute
  '/_authenticated/researcher/downloads': typeof AuthenticatedResearcherDownloadsRoute
  '/_authenticated/researcher/explorer': typeof AuthenticatedResearcherExplorerRoute
  '/_authenticated/researcher/home': typeof AuthenticatedResearcherHomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/patient/dashboard'
    | '/patient/data-nft'
    | '/patient/earnings'
    | '/patient/goals'
    | '/patient/insights'
    | '/patient/interactions'
    | '/patient/leaderboard'
    | '/patient/marketplace'
    | '/patient/places'
    | '/patient/privacy'
    | '/patient/redeem'
    | '/patient/referrals'
    | '/patient/timeline'
    | '/patient/vault'
    | '/researcher/analytics'
    | '/researcher/campaigns'
    | '/researcher/contracts'
    | '/researcher/create'
    | '/researcher/downloads'
    | '/researcher/explorer'
    | '/researcher/home'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/patient/dashboard'
    | '/patient/data-nft'
    | '/patient/earnings'
    | '/patient/goals'
    | '/patient/insights'
    | '/patient/interactions'
    | '/patient/leaderboard'
    | '/patient/marketplace'
    | '/patient/places'
    | '/patient/privacy'
    | '/patient/redeem'
    | '/patient/referrals'
    | '/patient/timeline'
    | '/patient/vault'
    | '/researcher/analytics'
    | '/researcher/campaigns'
    | '/researcher/contracts'
    | '/researcher/create'
    | '/researcher/downloads'
    | '/researcher/explorer'
    | '/researcher/home'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/profile'
    | '/_authenticated/patient/dashboard'
    | '/_authenticated/patient/data-nft'
    | '/_authenticated/patient/earnings'
    | '/_authenticated/patient/goals'
    | '/_authenticated/patient/insights'
    | '/_authenticated/patient/interactions'
    | '/_authenticated/patient/leaderboard'
    | '/_authenticated/patient/marketplace'
    | '/_authenticated/patient/places'
    | '/_authenticated/patient/privacy'
    | '/_authenticated/patient/redeem'
    | '/_authenticated/patient/referrals'
    | '/_authenticated/patient/timeline'
    | '/_authenticated/patient/vault'
    | '/_authenticated/researcher/analytics'
    | '/_authenticated/researcher/campaigns'
    | '/_authenticated/researcher/contracts'
    | '/_authenticated/researcher/create'
    | '/_authenticated/researcher/downloads'
    | '/_authenticated/researcher/explorer'
    | '/_authenticated/researcher/home'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/researcher/home': {
      id: '/_authenticated/researcher/home'
      path: '/researcher/home'
      fullPath: '/researcher/home'
      preLoaderRoute: typeof AuthenticatedResearcherHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/researcher/explorer': {
      id: '/_authenticated/researcher/explorer'
      path: '/researcher/explorer'
      fullPath: '/researcher/explorer'
      preLoaderRoute: typeof AuthenticatedResearcherExplorerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/researcher/downloads': {
      id: '/_authenticated/researcher/downloads'
      path: '/researcher/downloads'
      fullPath: '/researcher/downloads'
      preLoaderRoute: typeof AuthenticatedResearcherDownloadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/researcher/create': {
      id: '/_authenticated/researcher/create'
      path: '/researcher/create'
      fullPath: '/researcher/create'
      preLoaderRoute: typeof AuthenticatedResearcherCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/researcher/contracts': {
      id: '/_authenticated/researcher/contracts'
      path: '/researcher/contracts'
      fullPath: '/researcher/contracts'
      preLoaderRoute: typeof AuthenticatedResearcherContractsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/researcher/campaigns': {
      id: '/_authenticated/researcher/campaigns'
      path: '/researcher/campaigns'
      fullPath: '/researcher/campaigns'
      preLoaderRoute: typeof AuthenticatedResearcherCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/researcher/analytics': {
      id: '/_authenticated/researcher/analytics'
      path: '/researcher/analytics'
      fullPath: '/researcher/analytics'
      preLoaderRoute: typeof AuthenticatedResearcherAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/vault': {
      id: '/_authenticated/patient/vault'
      path: '/patient/vault'
      fullPath: '/patient/vault'
      preLoaderRoute: typeof AuthenticatedPatientVaultRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/timeline': {
      id: '/_authenticated/patient/timeline'
      path: '/patient/timeline'
      fullPath: '/patient/timeline'
      preLoaderRoute: typeof AuthenticatedPatientTimelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/referrals': {
      id: '/_authenticated/patient/referrals'
      path: '/patient/referrals'
      fullPath: '/patient/referrals'
      preLoaderRoute: typeof AuthenticatedPatientReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/redeem': {
      id: '/_authenticated/patient/redeem'
      path: '/patient/redeem'
      fullPath: '/patient/redeem'
      preLoaderRoute: typeof AuthenticatedPatientRedeemRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/privacy': {
      id: '/_authenticated/patient/privacy'
      path: '/patient/privacy'
      fullPath: '/patient/privacy'
      preLoaderRoute: typeof AuthenticatedPatientPrivacyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/places': {
      id: '/_authenticated/patient/places'
      path: '/patient/places'
      fullPath: '/patient/places'
      preLoaderRoute: typeof AuthenticatedPatientPlacesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/marketplace': {
      id: '/_authenticated/patient/marketplace'
      path: '/patient/marketplace'
      fullPath: '/patient/marketplace'
      preLoaderRoute: typeof AuthenticatedPatientMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/leaderboard': {
      id: '/_authenticated/patient/leaderboard'
      path: '/patient/leaderboard'
      fullPath: '/patient/leaderboard'
      preLoaderRoute: typeof AuthenticatedPatientLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/interactions': {
      id: '/_authenticated/patient/interactions'
      path: '/patient/interactions'
      fullPath: '/patient/interactions'
      preLoaderRoute: typeof AuthenticatedPatientInteractionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/insights': {
      id: '/_authenticated/patient/insights'
      path: '/patient/insights'
      fullPath: '/patient/insights'
      preLoaderRoute: typeof AuthenticatedPatientInsightsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/goals': {
      id: '/_authenticated/patient/goals'
      path: '/patient/goals'
      fullPath: '/patient/goals'
      preLoaderRoute: typeof AuthenticatedPatientGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/earnings': {
      id: '/_authenticated/patient/earnings'
      path: '/patient/earnings'
      fullPath: '/patient/earnings'
      preLoaderRoute: typeof AuthenticatedPatientEarningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/data-nft': {
      id: '/_authenticated/patient/data-nft'
      path: '/patient/data-nft'
      fullPath: '/patient/data-nft'
      preLoaderRoute: typeof AuthenticatedPatientDataNftRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patient/dashboard': {
      id: '/_authenticated/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof AuthenticatedPatientDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedPatientDashboardRoute: typeof AuthenticatedPatientDashboardRoute
  AuthenticatedPatientDataNftRoute: typeof AuthenticatedPatientDataNftRoute
  AuthenticatedPatientEarningsRoute: typeof AuthenticatedPatientEarningsRoute
  AuthenticatedPatientGoalsRoute: typeof AuthenticatedPatientGoalsRoute
  AuthenticatedPatientInsightsRoute: typeof AuthenticatedPatientInsightsRoute
  AuthenticatedPatientInteractionsRoute: typeof AuthenticatedPatientInteractionsRoute
  AuthenticatedPatientLeaderboardRoute: typeof AuthenticatedPatientLeaderboardRoute
  AuthenticatedPatientMarketplaceRoute: typeof AuthenticatedPatientMarketplaceRoute
  AuthenticatedPatientPlacesRoute: typeof AuthenticatedPatientPlacesRoute
  AuthenticatedPatientPrivacyRoute: typeof AuthenticatedPatientPrivacyRoute
  AuthenticatedPatientRedeemRoute: typeof AuthenticatedPatientRedeemRoute
  AuthenticatedPatientReferralsRoute: typeof AuthenticatedPatientReferralsRoute
  AuthenticatedPatientTimelineRoute: typeof AuthenticatedPatientTimelineRoute
  AuthenticatedPatientVaultRoute: typeof AuthenticatedPatientVaultRoute
  AuthenticatedResearcherAnalyticsRoute: typeof AuthenticatedResearcherAnalyticsRoute
  AuthenticatedResearcherCampaignsRoute: typeof AuthenticatedResearcherCampaignsRoute
  AuthenticatedResearcherContractsRoute: typeof AuthenticatedResearcherContractsRoute
  AuthenticatedResearcherCreateRoute: typeof AuthenticatedResearcherCreateRoute
  AuthenticatedResearcherDownloadsRoute: typeof AuthenticatedResearcherDownloadsRoute
  AuthenticatedResearcherExplorerRoute: typeof AuthenticatedResearcherExplorerRoute
  AuthenticatedResearcherHomeRoute: typeof AuthenticatedResearcherHomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedPatientDashboardRoute: AuthenticatedPatientDashboardRoute,
  AuthenticatedPatientDataNftRoute: AuthenticatedPatientDataNftRoute,
  AuthenticatedPatientEarningsRoute: AuthenticatedPatientEarningsRoute,
  AuthenticatedPatientGoalsRoute: AuthenticatedPatientGoalsRoute,
  AuthenticatedPatientInsightsRoute: AuthenticatedPatientInsightsRoute,
  AuthenticatedPatientInteractionsRoute: AuthenticatedPatientInteractionsRoute,
  AuthenticatedPatientLeaderboardRoute: AuthenticatedPatientLeaderboardRoute,
  AuthenticatedPatientMarketplaceRoute: AuthenticatedPatientMarketplaceRoute,
  AuthenticatedPatientPlacesRoute: AuthenticatedPatientPlacesRoute,
  AuthenticatedPatientPrivacyRoute: AuthenticatedPatientPrivacyRoute,
  AuthenticatedPatientRedeemRoute: AuthenticatedPatientRedeemRoute,
  AuthenticatedPatientReferralsRoute: AuthenticatedPatientReferralsRoute,
  AuthenticatedPatientTimelineRoute: AuthenticatedPatientTimelineRoute,
  AuthenticatedPatientVaultRoute: AuthenticatedPatientVaultRoute,
  AuthenticatedResearcherAnalyticsRoute: AuthenticatedResearcherAnalyticsRoute,
  AuthenticatedResearcherCampaignsRoute: AuthenticatedResearcherCampaignsRoute,
  AuthenticatedResearcherContractsRoute: AuthenticatedResearcherContractsRoute,
  AuthenticatedResearcherCreateRoute: AuthenticatedResearcherCreateRoute,
  AuthenticatedResearcherDownloadsRoute: AuthenticatedResearcherDownloadsRoute,
  AuthenticatedResearcherExplorerRoute: AuthenticatedResearcherExplorerRoute,
  AuthenticatedResearcherHomeRoute: AuthenticatedResearcherHomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
